#!/bin/sh

echo "TEST FOR CHALLENGE 1 (SUPER WORD SEARCH)"
cd ./q1
/usr/bin/env python3 -B main.py config/example1.yaml
/usr/bin/env python3 -B main.py config/example2.yaml
/usr/bin/env python3 -B main.py config/summer.yaml
cd ..

echo "TEST FOR CHALLENGE 2 (NEAREST NEIGHBORS ALGORITHM)"
cd ./q2
/usr/bin/env python3 -B main.py 1.0 points.txt
cd ..